# Generated by Django 5.2.5 on 2025-08-07 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: list = []  # type: ignore[var-annotated]

    operations = [
        migrations.CreateModel(
            name='AssetPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair_id', models.IntegerField(unique=True)),
                ('primary_currency_ticker', models.CharField(max_length=10)),
                ('secondary_currency_ticker', models.CharField(max_length=10)),
                ('primary_currency_name', models.CharField(max_length=100)),
                ('secondary_currency_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_fetched', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'asset_pairs',
                'ordering': ['primary_currency_ticker', 'secondary_currency_ticker'],
            },
        ),
        migrations.CreateModel(
            name='BotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                (
                    'bot_type',
                    models.CharField(
                        choices=[('randy', 'Randy - Random Trading Bot'), ('strategic', 'Strategic Trading Bot'),
                                 ('llm', 'LLM-Powered Trading Bot')],
                        default='randy',
                        max_length=50
                    )
                ),
                (
                    'status',
                    models.CharField(
                        choices=[('active', 'Active'), ('paused', 'Paused'), ('stopped', 'Stopped')],
                        default='stopped',
                        max_length=20
                    )
                ),
                ('api_username', models.CharField(max_length=100)),
                ('api_password', models.CharField(max_length=255)),
                ('api_base_url', models.URLField(default='https://thenewboston.network/api')),
                ('max_spend_per_trade', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('min_balance_required', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                (
                    'sell_probability',
                    models.FloatField(default=0.25, help_text='Probability of selling vs buying (0-1)')
                ),
                ('interval_seconds', models.IntegerField(default=60, help_text='Seconds between bot runs')),
                ('max_iterations', models.IntegerField(default=0, help_text='Max iterations (0 = infinite)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('total_runs', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'bot_configs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BotRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                (
                    'status',
                    models.CharField(
                        choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'),
                                 ('cancelled', 'Cancelled')],
                        max_length=20
                    )
                ),
                ('iterations_completed', models.IntegerField(default=0)),
                ('errors', models.TextField(blank=True)),
                (
                    'bot_config',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='trading.botconfig'
                    )
                ),
            ],
            options={
                'db_table': 'bot_runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TradeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=18)),
                ('total_value', models.DecimalField(decimal_places=8, max_digits=18)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.CharField(blank=True, max_length=100)),
                (
                    'status',
                    models.CharField(
                        choices=[('pending', 'Pending'), ('executed', 'Executed'), ('cancelled', 'Cancelled'),
                                 ('failed', 'Failed')],
                        max_length=20
                    )
                ),
                ('response_data', models.JSONField(blank=True, null=True)),
                (
                    'asset_pair',
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trading.assetpair')
                ),
                (
                    'bot_run',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trading.botrun'
                    )
                ),
            ],
            options={
                'db_table': 'trade_logs',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='TradingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority pairs are selected first')),
                ('asset_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.assetpair')),
                (
                    'bot_config',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='trading_pairs',
                        to='trading.botconfig'
                    )
                ),
            ],
            options={
                'db_table': 'trading_pairs',
                'ordering': ['-priority'],
                'unique_together': {('bot_config', 'asset_pair')},
            },
        ),
    ]
